static const char *RcsId = "$Header:  $";
//+=============================================================================
//
// file :         PmacEthStateMachine.cpp
//
// description :  C++ source for the PmacEth and its alowed. 
//                method for commands and attributes
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
//
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <PmacEth.h>
#include <PmacEthClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace PmacEth_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_Position_allowed
// 
// description : 	Read/Write allowed for Position attribute.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_Position_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_Velocity_allowed
// 
// description : 	Read/Write allowed for Velocity attribute.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_Velocity_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_FollowErr_allowed
// 
// description : 	Read/Write allowed for FollowErr attribute.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_FollowErr_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_JogPlus_allowed
// 
// description : 	Execution allowed for JogPlus command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_JogPlus_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_JogMinus_allowed
// 
// description : 	Execution allowed for JogMinus command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_JogMinus_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_JogStop_allowed
// 
// description : 	Execution allowed for JogStop command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_JogStop_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_JogToPos_allowed
// 
// description : 	Execution allowed for JogToPos command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_JogToPos_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_DownloadFile_allowed
// 
// description : 	Execution allowed for DownloadFile command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_DownloadFile_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_UploadVars_allowed
// 
// description : 	Execution allowed for UploadVars command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_UploadVars_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_UploadProg_allowed
// 
// description : 	Execution allowed for UploadProg command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_UploadProg_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_ResetMotor_allowed
// 
// description : 	Execution allowed for ResetMotor command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_ResetMotor_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_HomeMotor_allowed
// 
// description : 	Execution allowed for HomeMotor command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_HomeMotor_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_HomeZeroMotor_allowed
// 
// description : 	Execution allowed for HomeZeroMotor command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_HomeZeroMotor_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_KillMotor_allowed
// 
// description : 	Execution allowed for KillMotor command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_KillMotor_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_AboutPmac_allowed
// 
// description : 	Execution allowed for AboutPmac command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_AboutPmac_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_FirmwareInfo_allowed
// 
// description : 	Execution allowed for FirmwareInfo command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_FirmwareInfo_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_JogDistFromPos_allowed
// 
// description : 	Execution allowed for JogDistFromPos command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_JogDistFromPos_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_JogDistFromCmdPos_allowed
// 
// description : 	Execution allowed for JogDistFromCmdPos command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_JogDistFromCmdPos_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_GetFeedrateOverride_allowed
// 
// description : 	Execution allowed for GetFeedrateOverride command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_GetFeedrateOverride_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_SetFeedrateOverride_allowed
// 
// description : 	Execution allowed for SetFeedrateOverride command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_SetFeedrateOverride_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_ClearAmplifFault_allowed
// 
// description : 	Execution allowed for ClearAmplifFault command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_ClearAmplifFault_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_GlobalReset_allowed
// 
// description : 	Execution allowed for GlobalReset command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_GlobalReset_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_SendCtrlChar_allowed
// 
// description : 	Execution allowed for SendCtrlChar command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_SendCtrlChar_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_GlobalStatus_allowed
// 
// description : 	Execution allowed for GlobalStatus command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_GlobalStatus_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_CoordSysStatus_allowed
// 
// description : 	Execution allowed for CoordSysStatus command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_CoordSysStatus_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_GetIVariable_allowed
// 
// description : 	Execution allowed for GetIVariable command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_GetIVariable_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_SetIVariable_allowed
// 
// description : 	Execution allowed for SetIVariable command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_SetIVariable_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_GetMVariable_allowed
// 
// description : 	Execution allowed for GetIVariable command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_GetMVariable_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
// //+----------------------------------------------------------------------------
// //
// // method : 		PmacEth::is_SetMVariable_allowed
// // 
// // description : 	Execution allowed for SetIVariable command.
// //
// //-----------------------------------------------------------------------------
bool PmacEth::is_SetMVariable_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_GetPVariable_allowed
// 
// description : 	Execution allowed for GetPVariable command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_GetPVariable_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
// //+----------------------------------------------------------------------------
// //
// // method : 		PmacEth::is_SetPVariable_allowed
// // 
// // description : 	Execution allowed for SetPVariable command.
// //
// //-----------------------------------------------------------------------------
bool PmacEth::is_SetPVariable_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_SaveIVars_allowed
// 
// description : 	Execution allowed for SaveIVars command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_SaveIVars_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_GetMotorNo_allowed
// 
// description : 	Execution allowed for GetMotorNo command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_GetMotorNo_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_SetMotorNo_allowed
// 
// description : 	Execution allowed for SetMotorNo command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_SetMotorNo_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_DefineCoordSys_allowed
// 
// description : 	Execution allowed for DefineCoordSys command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_DefineCoordSys_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_GetCoordSys_allowed
// 
// description : 	Execution allowed for GetCoordSys command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_GetCoordSys_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_GetIPaddr_allowed
// 
// description : 	Execution allowed for GetIPaddr command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_GetIPaddr_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_SetIPaddr_allowed
// 
// description : 	Execution allowed for SetIPaddr command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_SetIPaddr_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_GlobalResetReinit_allowed
// 
// description : 	Execution allowed for GlobalResetReinit command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_GlobalResetReinit_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_OpenConnection_allowed
// 
// description : 	Execution allowed for OpenConnection command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_OpenConnection_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::ON)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_CloseConnection_allowed
// 
// description : 	Execution allowed for CloseConnection command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_CloseConnection_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_OnlineCmd_allowed
// 
// description : 	Execution allowed for OnlineCmd command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_OnlineCmd_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_EnablePLC_allowed
// 
// description : 	Execution allowed for EnablePLC command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_EnablePLC_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_DisablePLC_allowed
// 
// description : 	Execution allowed for DisablePLC command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_DisablePLC_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_RunMotionProg_allowed
// 
// description : 	Execution allowed for RunMotionProg command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_RunMotionProg_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_GetMotorPos_allowed
// 
// description : 	Execution allowed for GetMotorPos command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_GetMotorPos_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

//+----------------------------------------------------------------------------
//
// method : 		PmacEth::is_ListPLC_allowed
// 
// description : 	Execution allowed for ListPLC command.
//
//-----------------------------------------------------------------------------
bool PmacEth::is_ListPLC_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

}	// namespace PmacEth_ns
