/*----- PROTECTED REGION ID(PmacEth.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        PmacEth.cpp
//
// description : C++ source for the PmacEth class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               PmacEth are implemented in this file.
//
// project :     PMAC over Ethernet
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <tango.h>
#include <PmacEth.h>
#include <PmacEthClass.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "comm_lib/pcommx.h"
#include <iostream>
#include <fstream>
#include <vector>
#include <unistd.h>

/*----- PROTECTED REGION END -----*/	//	PmacEth.cpp

/**
 *  PmacEth class description:
 *    Device Server for PMAC over Ethernet
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name         |  Method name
//================================================================
//  State                |  Inherited (no method)
//  Status               |  Inherited (no method)
//  OpenConnection       |  open_connection
//  CloseConnection      |  close_connection
//  AboutPmac            |  about_pmac
//  FirmwareInfo         |  firmware_info
//  GetIPaddr            |  get_ipaddr
//  SetIPaddr            |  set_ipaddr
//  JogPlus              |  jog_plus
//  JogMinus             |  jog_minus
//  JogStop              |  jog_stop
//  JogToPos             |  jog_to_pos
//  JogDistFromPos       |  jog_dist_from_pos
//  JogDistFromCmdPos    |  jog_dist_from_cmd_pos
//  GetFeedrateOverride  |  get_feedrate_override
//  SetFeedrateOverride  |  set_feedrate_override
//  ResetMotor           |  reset_motor
//  HomeMotor            |  home_motor
//  HomeZeroMotor        |  home_zero_motor
//  KillMotor            |  kill_motor
//  ClearAmplifFault     |  clear_amplif_fault
//  GlobalReset          |  global_reset
//  GlobalResetReinit    |  global_reset_reinit
//  SendCtrlChar         |  send_ctrl_char
//  GlobalStatus         |  global_status
//  CoordSysStatus       |  coord_sys_status
//  GetIVariable         |  get_ivariable
//  SetIVariable         |  set_ivariable
//  GetMVariable         |  get_mvariable
//  SetMVariable         |  set_mvariable
//  GetPVariable         |  get_pvariable
//  GetPVariableRange    |  get_pvariable_range
//  SetPVariable         |  set_pvariable
//  SaveIVars            |  save_ivars
//  DownloadFile         |  download_file
//  UploadVars           |  upload_vars
//  UploadProg           |  upload_prog
//  GetMotorNo           |  get_motor_no
//  SetMotorNo           |  set_motor_no
//  DefineCoordSys       |  define_coord_sys
//  GetCoordSys          |  get_coord_sys
//  OnlineCmd            |  online_cmd
//  EnablePLC            |  enable_plc
//  DisablePLC           |  disable_plc
//  RunMotionProg        |  run_motion_prog
//  GetMotorPos          |  get_motor_pos
//  ListPLC              |  list_plc
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  Position   |  Tango::DevLong	Scalar
//  Velocity   |  Tango::DevLong	Scalar
//  FollowErr  |  Tango::DevLong	Scalar
//================================================================

namespace PmacEth_ns
{
/*----- PROTECTED REGION ID(PmacEth::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	PmacEth::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : PmacEth::PmacEth()
 *	Description : Constructors for a Tango device
 *                implementing the classPmacEth
 */
//--------------------------------------------------------
PmacEth::PmacEth(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(PmacEth::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	PmacEth::constructor_1
}
//--------------------------------------------------------
PmacEth::PmacEth(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(PmacEth::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	PmacEth::constructor_2
}
//--------------------------------------------------------
PmacEth::PmacEth(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(PmacEth::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	PmacEth::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : PmacEth::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void PmacEth::delete_device()
{
	DEBUG_STREAM << "PmacEth::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	//	Delete device's allocated object
  delete attr_Position_read;
  delete attr_Velocity_read;
  delete attr_FollowErr_read;

	/*----- PROTECTED REGION END -----*/	//	PmacEth::delete_device
}

//--------------------------------------------------------
/**
 *	Method      : PmacEth::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void PmacEth::init_device()
{
	DEBUG_STREAM << "PmacEth::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	

	/*----- PROTECTED REGION END -----*/	//	PmacEth::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	

	/*----- PROTECTED REGION ID(PmacEth::init_device) ENABLED START -----*/
	
	//	Initialize device
	attr_Position_read=new Tango::DevLong;
	attr_Velocity_read=new Tango::DevLong;
	attr_FollowErr_read=new Tango::DevLong;
	sockfd=-1;
        try
        {
            open_connection();
        }
        catch (...)
        {
            set_state(Tango::OFF);
        }

	/*----- PROTECTED REGION END -----*/	//	PmacEth::init_device
}

//--------------------------------------------------------
/**
 *	Method      : PmacEth::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void PmacEth::get_device_property()
{
	/*----- PROTECTED REGION ID(PmacEth::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	

	/*----- PROTECTED REGION END -----*/	//	PmacEth::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("IP_address"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on PmacEthClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		PmacEthClass	*ds_class =
			(static_cast<PmacEthClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize IP_address from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  iP_address;
		else {
			//	Try to initialize IP_address from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  iP_address;
		}
		//	And try to extract IP_address value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  iP_address;

	}

	/*----- PROTECTED REGION ID(PmacEth::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	PmacEth::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : PmacEth::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void PmacEth::always_executed_hook()
{
	INFO_STREAM << "PmacEth::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	

	/*----- PROTECTED REGION END -----*/	//	PmacEth::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : PmacEth::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void PmacEth::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "PmacEth::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(PmacEth::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	//	Add your own code here

	/*----- PROTECTED REGION END -----*/	//	PmacEth::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute Position related method
 *	Description: Current position of selected motor in encoder counts
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void PmacEth::read_Position(Tango::Attribute &attr)
{
	DEBUG_STREAM << "PmacEth::read_Position(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(PmacEth::read_Position) ENABLED START -----*/
	char buffer[2048];

	strcpy(buffer,"P");
	if(pmac_get_response(sockfd,buffer,2048)<0)
	  Tango::Except::throw_exception("Error:read_Position","Can't read from device","Device server read attribute",Tango::ERR);
	*attr_Position_read=atoi(buffer);
	attr.set_value(attr_Position_read);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::read_Position
}
//--------------------------------------------------------
/**
 *	Read attribute Velocity related method
 *	Description: Velocity of selected motor in counts/second
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void PmacEth::read_Velocity(Tango::Attribute &attr)
{
	DEBUG_STREAM << "PmacEth::read_Velocity(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(PmacEth::read_Velocity) ENABLED START -----*/
	char buffer[2048];

	strcpy(buffer,"V");
	if(pmac_get_response(sockfd,buffer,2048)<0)
	  Tango::Except::throw_exception("Error:read_Velocity","Can't read from device","Device server read attribute",Tango::ERR);
	*attr_Velocity_read=atoi(buffer);
	attr.set_value(attr_Velocity_read);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::read_Velocity
}
//--------------------------------------------------------
/**
 *	Read attribute FollowErr related method
 *	Description: Following error of motor in encoder counts
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void PmacEth::read_FollowErr(Tango::Attribute &attr)
{
	DEBUG_STREAM << "PmacEth::read_FollowErr(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(PmacEth::read_FollowErr) ENABLED START -----*/
	char buffer[2048];

	strcpy(buffer,"F");
	if(pmac_get_response(sockfd,buffer,2048)<0)
	  Tango::Except::throw_exception("Error:read_FollowErr","Can't read from device","Device server read attribute",Tango::ERR);
	*attr_FollowErr_read=atoi(buffer);
	attr.set_value(attr_FollowErr_read);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::read_FollowErr
}

//--------------------------------------------------------
/**
 *	Method      : PmacEth::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void PmacEth::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(PmacEth::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	PmacEth::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command OpenConnection related method
 *	Description: Open TCP connection with the PMAC controller card.
 *               The device property IP_address must contain the actual PMAC IP address.
 *
 */
//--------------------------------------------------------
void PmacEth::open_connection()
{
	DEBUG_STREAM << "PmacEth::OpenConnection()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::open_connection) ENABLED START -----*/
	
	//	Add your own code
	if((sockfd=open_pmac_device(iP_address.c_str()))<0)
	  Tango::Except::throw_exception("Error:open_connection","Can't connect to device","Device server OpenConnection",Tango::ERR);
	else
	  set_state(Tango::ON);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::open_connection
}
//--------------------------------------------------------
/**
 *	Command CloseConnection related method
 *	Description: Close current TCP connection between PC & PMAC.
 *
 */
//--------------------------------------------------------
void PmacEth::close_connection()
{
	DEBUG_STREAM << "PmacEth::CloseConnection()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::close_connection) ENABLED START -----*/
	
	//	Add your own code
	if(sockfd<0)
	  Tango::Except::throw_exception("Error:close_connection","Invalid socket","Device server CloseConnection",Tango::ERR);
	else
	  {
	    if(close_pmac_device(sockfd)==0)
	      set_state(Tango::OFF);
	  }

	/*----- PROTECTED REGION END -----*/	//	PmacEth::close_connection
}
//--------------------------------------------------------
/**
 *	Command AboutPmac related method
 *	Description: Display information about PMAC controller card.
 *
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevString PmacEth::about_pmac()
{
	DEBUG_STREAM << "PmacEth::AboutPmac()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::about_pmac) ENABLED START -----*/
	
	//	Add your own code
	//	POGO has generated a method core with argout allocation.
	//	If you would like to use a static reference without copying,
	//	See "TANGO Device Server Programmer's Manual"
	//		(chapter : Writing a TANGO DS / Exchanging data)
	//------------------------------------------------------------
	Tango::DevString	argout  = new char[256];
	//strcpy(argout, "dummy");
	DEBUG_STREAM << "PmacEth::about_pmac(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[256];

	strcpy(buf,"TYPE");
	if(pmac_get_response(sockfd,buf,256)<0)
	  strcpy(argout,"error");
	else
	  strcpy(argout,buf);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::about_pmac
	return argout;
}
//--------------------------------------------------------
/**
 *	Command FirmwareInfo related method
 *	Description: Display information about PMAC firmware in  use.
 *
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevString PmacEth::firmware_info()
{
	DEBUG_STREAM << "PmacEth::FirmwareInfo()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::firmware_info) ENABLED START -----*/
	
	//	Add your own code
	//	POGO has generated a method core with argout allocation.
	//	If you would like to use a static reference without copying,
	//	See "TANGO Device Server Programmer's Manual"
	//		(chapter : Writing a TANGO DS / Exchanging data)
	//------------------------------------------------------------
	Tango::DevString	argout  = new char[256];
	//strcpy(argout, "dummy");
	DEBUG_STREAM << "PmacEth::firmware_info(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[256];
	int prev_len,i;

	strcpy(buf,"VERSION");
	if((i=pmac_get_response(sockfd,buf,256))<0)
	  strcpy(argout,"error");
	else
	  {
	    memcpy(argout,buf,i-2);
	    argout[i-2]=0x20;
	    argout[i-1]=0x00;
	    prev_len=i-1;
	    strcpy(buf,"DATE");
	    if((i=pmac_get_response(sockfd,buf,256))<0)
	      {	      
		strcpy(buf,"fw date error");
		i=13;
	      }
	    memcpy(argout+prev_len,buf,i-2);
	    argout[prev_len+i-2]=0x20;
	    argout[prev_len+i-1]=0x00;
	    prev_len+=i-1;
	    strcpy(buf,"CHECKSUM");
	    if((i=pmac_get_response(sockfd,buf,256))<0)
	      {	      
		strcpy(buf,"fw cksum error");
		i=14;
	      }
	    memcpy(argout+prev_len,buf,i);
	    argout[prev_len+i]=0x00;
	  }

	/*----- PROTECTED REGION END -----*/	//	PmacEth::firmware_info
	return argout;
}
//--------------------------------------------------------
/**
 *	Command GetIPaddr related method
 *	Description: Get current/set PMAC IP address from controller card.
 *
 *	@returns PMAC IP address read from controller card.
 */
//--------------------------------------------------------
Tango::DevString PmacEth::get_ipaddr()
{
	DEBUG_STREAM << "PmacEth::GetIPaddr()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::get_ipaddr) ENABLED START -----*/
	
	//	Add your own code
	//	POGO has generated a method core with argout allocation.
	//	If you would like to use a static reference without copying,
	//	See "TANGO Device Server Programmer's Manual"
	//		(chapter : Writing a TANGO DS / Exchanging data)
	//------------------------------------------------------------
	Tango::DevString	argout  = new char[16];
	//strcpy(argout, "dummy");
	DEBUG_STREAM << "PmacEth::get_ipaddr(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[16];
	
	if(pmac_get_ip(sockfd,buf)<0)
	  strcpy(argout,"error");
	else
	  strcpy(argout,buf);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::get_ipaddr
	return argout;
}
//--------------------------------------------------------
/**
 *	Command SetIPaddr related method
 *	Description: dotted decimal form.
 *
 *	@param argin PMAC IP address to set; dotted decimal form.
 */
//--------------------------------------------------------
void PmacEth::set_ipaddr(Tango::DevString argin)
{
	DEBUG_STREAM << "PmacEth::SetIPaddr()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::set_ipaddr) ENABLED START -----*/
	
	//	Add your own code
	/* need more argin tests! */
	int i,ctr;

	if((strlen(argin)>15) || (strlen(argin)<7))
	  Tango::Except::throw_exception("Error:set_ipaddr","IP address out of bounds","Device server SetIPaddr",Tango::ERR);
	else
	  {
	    ctr=0;
	    for(i=0;i<strlen(argin);i++)
	      if(argin[i]=='.')
		ctr++;
	    if(ctr!=3)
	      Tango::Except::throw_exception("Error:set_ipaddr","bad IP address","Device server SetIPaddr",Tango::ERR);
	    else
	      if(pmac_set_ip(sockfd,argin)<0)
		Tango::Except::throw_exception("Error:set_ipaddr","Can't set IP address","Device server SetIPaddr",Tango::ERR);
	  }

	/*----- PROTECTED REGION END -----*/	//	PmacEth::set_ipaddr
}
//--------------------------------------------------------
/**
 *	Command JogPlus related method
 *	Description: Jog motor indefinitely in the positive direction.
 *
 *	@param argin Nr of motor to jog plus
 */
//--------------------------------------------------------
void PmacEth::jog_plus(const Tango::DevVarShortArray *argin)
{
	DEBUG_STREAM << "PmacEth::JogPlus()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::jog_plus) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];

	if (argin->length() == 0)
	  strcpy(buf,"J+");
	else if (argin->length() == 1)
	  sprintf(buf,"#%dJ+",(*argin)[0]);
	else
	  Tango::Except::throw_exception("Error:jog_plus","Argin array too long","Device server JogPlus",Tango::ERR);

	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:jog_plus","Can't move motor","Device server JogPlus",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::jog_plus
}
//--------------------------------------------------------
/**
 *	Command JogMinus related method
 *	Description: Jog motor indefinitely in the negative direction.
 *
 *	@param argin Nr of motor to jog minus
 */
//--------------------------------------------------------
void PmacEth::jog_minus(const Tango::DevVarShortArray *argin)
{
	DEBUG_STREAM << "PmacEth::JogMinus()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::jog_minus) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];

	if (argin->length() == 0)
	  strcpy(buf,"J-");
	else if (argin->length() == 1)
	  sprintf(buf,"#%dJ-",(*argin)[0]);
	else
	  Tango::Except::throw_exception("Error:jog_minus","Argin array too long","Device server JogMinus",Tango::ERR);

	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:jog_minus","Can't move motor","Device server JogMinus",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::jog_minus
}
//--------------------------------------------------------
/**
 *	Command JogStop related method
 *	Description: Stop jogging motor.
 *               Restore position control if motor was killed.
 *
 *	@param argin Nr of motor to jog stop
 */
//--------------------------------------------------------
void PmacEth::jog_stop(const Tango::DevVarShortArray *argin)
{
	DEBUG_STREAM << "PmacEth::JogStop()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::jog_stop) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	if (argin->length() == 0)
	  strcpy(buf,"J/");
	else if (argin->length() == 1)
	  sprintf(buf,"#%dJ/",(*argin)[0]);
	else
	  Tango::Except::throw_exception("Error:jog_stop","Argin array too long","Device server JogToPos",Tango::ERR);

	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:jog_stop","Can't stop motor","Device server JogStop",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::jog_stop
}
//--------------------------------------------------------
/**
 *	Command JogToPos related method
 *	Description: Jog motor to specified position.
 *
 *	@param argin Position motor should move to, in encoder counts.
 */
//--------------------------------------------------------
void PmacEth::jog_to_pos(const Tango::DevVarDoubleArray *argin)
{
	DEBUG_STREAM << "PmacEth::JogToPos()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::jog_to_pos) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	if (argin->length() == 1)
	  sprintf(buf,"J=%f",(*argin)[0]);
	else if (argin->length() == 2)
	  sprintf(buf,"#%dJ=%f",int((*argin)[0]),(*argin)[1]);
	else
	  Tango::Except::throw_exception("Error:jog_to_pos","Argin array too long","Device server JogToPos",Tango::ERR);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:jog_to_pos","Can't move motor","Device server JogToPos",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::jog_to_pos
}
//--------------------------------------------------------
/**
 *	Command JogDistFromPos related method
 *	Description: Jog motor specified distance from the current actual position.
 *
 *	@param argin Distance from current actual position, in encoder counts.
 */
//--------------------------------------------------------
void PmacEth::jog_dist_from_pos(Tango::DevLong argin)
{
	DEBUG_STREAM << "PmacEth::JogDistFromPos()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::jog_dist_from_pos) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	
	sprintf(buf,"J^%d",argin);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:jog_dist_from_pos","Can't move motor","Device server JogDistFromPos",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::jog_dist_from_pos
}
//--------------------------------------------------------
/**
 *	Command JogDistFromCmdPos related method
 *	Description: Jog motor specified distance from the current commanded position.
 *
 *	@param argin Distance from current commanded position, in encoder counts.
 */
//--------------------------------------------------------
void PmacEth::jog_dist_from_cmd_pos(Tango::DevLong argin)
{
	DEBUG_STREAM << "PmacEth::JogDistFromCmdPos()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::jog_dist_from_cmd_pos) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];

	sprintf(buf,"J:%d",argin);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:jog_dist_from_cmd_pos","Can't move motor","Device server JogDistFromCmdPos",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::jog_dist_from_cmd_pos
}
//--------------------------------------------------------
/**
 *	Command GetFeedrateOverride related method
 *	Description: Report current feedrate override value.
 *
 *	@returns Feedrate override in percents.
 */
//--------------------------------------------------------
Tango::DevDouble PmacEth::get_feedrate_override()
{
	DEBUG_STREAM << "PmacEth::GetFeedrateOverride()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::get_feedrate_override) ENABLED START -----*/
	
	//	Add your own code
	Tango::DevDouble	argout ;
	DEBUG_STREAM << "PmacEth::get_feedrate_override(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[16];

	strcpy(buf,"%");
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:get_feedrate_override","Can't get feedrate override","Device server GetFeedrateOverride",Tango::ERR);
	
	argout=atof(buf);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::get_feedrate_override
	return argout;
}
//--------------------------------------------------------
/**
 *	Command SetFeedrateOverride related method
 *	Description: Set feedrate override (percentage).
 *
 *	@param argin Feedrate override in percents.
 */
//--------------------------------------------------------
void PmacEth::set_feedrate_override(Tango::DevFloat argin)
{
	DEBUG_STREAM << "PmacEth::SetFeedrateOverride()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::set_feedrate_override) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];

	sprintf(buf,"%%%f",argin);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:set_feedrate_override","Can't set feedrate override","Device server SetFeedrateOverride",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::set_feedrate_override
}
//--------------------------------------------------------
/**
 *	Command ResetMotor related method
 *	Description: Reset feedback device(s) and phasing.
 *
 *	@param argin Nr of motor to reset
 */
//--------------------------------------------------------
void PmacEth::reset_motor(const Tango::DevVarShortArray *argin)
{
	DEBUG_STREAM << "PmacEth::ResetMotor()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::reset_motor) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	if (argin->length() == 0)
	  strcpy(buf,"$");
	else if (argin->length() == 1)
	  sprintf(buf,"#%d$",(*argin)[0]);
	else
	  Tango::Except::throw_exception("Error:reset_motor","Argin array too long","Device server ResetMotor",Tango::ERR);
	
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:reset_motor","Can't reset motor","Device server ResetMotor",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::reset_motor
}
//--------------------------------------------------------
/**
 *	Command HomeMotor related method
 *	Description: Perform homing routine for current motor.
 *
 *	@param argin Nr of motor to home
 */
//--------------------------------------------------------
void PmacEth::home_motor(const Tango::DevVarShortArray *argin)
{
	DEBUG_STREAM << "PmacEth::HomeMotor()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::home_motor) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	if (argin->length() == 0)
	  strcpy(buf,"HM");
	else if (argin->length() == 1)
	  sprintf(buf,"#%dHM",(*argin)[0]);
	else
	  Tango::Except::throw_exception("Error:home_motor","Argin array too long","Device server HomeMotor",Tango::ERR);

	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:home_motor","Can't home motor","Device server HomeMotor",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::home_motor
}
//--------------------------------------------------------
/**
 *	Command HomeZeroMotor related method
 *	Description: Perform zero-move routine for current motor.
 *
 *	@param argin Nr of motor to zero home
 */
//--------------------------------------------------------
void PmacEth::home_zero_motor(const Tango::DevVarShortArray *argin)
{
	DEBUG_STREAM << "PmacEth::HomeZeroMotor()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::home_zero_motor) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];

	if (argin->length() == 0)
	  strcpy(buf,"HMZ");
	else if (argin->length() == 1)
	  sprintf(buf,"#%dHMZ",(*argin)[0]);
	else
	  Tango::Except::throw_exception("Error:home_zero_motor","Argin array too long","Device server HomeZeroMotor",Tango::ERR);

	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:home_zero_motor","Can't home motor","Device server HomeZeroMotor",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::home_zero_motor
}
//--------------------------------------------------------
/**
 *	Command KillMotor related method
 *	Description: Kill output for current motor.
 *
 *	@param argin Nr of motor to kill
 */
//--------------------------------------------------------
void PmacEth::kill_motor(const Tango::DevVarShortArray *argin)
{
	DEBUG_STREAM << "PmacEth::KillMotor()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::kill_motor) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	if (argin->length() == 0)
	  strcpy(buf,"K");
	else if (argin->length() == 1)
	  sprintf(buf,"#%dK",(*argin)[0]);
	else
	  Tango::Except::throw_exception("Error:kill_motor","Argin array too long","Device server KillMotor",Tango::ERR);

	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:kill_motor","Can't kill motor","Device server KillMotor",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::kill_motor
}
//--------------------------------------------------------
/**
 *	Command ClearAmplifFault related method
 *	Description: Clear Geo amplifier fault display. (Geo PMAC only)
 *
 */
//--------------------------------------------------------
void PmacEth::clear_amplif_fault()
{
	DEBUG_STREAM << "PmacEth::ClearAmplifFault()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::clear_amplif_fault) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	
	strcpy(buf,"CLEARFAULT");
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:clear_amplif_fault","Can't clear amplif fault","Device server ClearAmplifFault",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::clear_amplif_fault
}
//--------------------------------------------------------
/**
 *	Command GlobalReset related method
 *	Description: Global reset, including all motors & coordinate systems.
 *
 */
//--------------------------------------------------------
void PmacEth::global_reset()
{
	DEBUG_STREAM << "PmacEth::GlobalReset()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::global_reset) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	
	strcpy(buf,"$$$");
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:global_reset","Can't reset card","Device server GlobalReset",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::global_reset
}
//--------------------------------------------------------
/**
 *	Command GlobalResetReinit related method
 *	Description: Global reset & re-initialize controller card.
 *
 */
//--------------------------------------------------------
void PmacEth::global_reset_reinit()
{
	DEBUG_STREAM << "PmacEth::GlobalResetReinit()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::global_reset_reinit) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	
	strcpy(buf,"$$$***");
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:global_reset_reinit","Can't reset & reinitialize card","Device server GlobalResetReinit",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::global_reset_reinit
}
//--------------------------------------------------------
/**
 *	Command SendCtrlChar related method
 *	Description: Send a control character to the PMAC card & get its response, if any.
 *
 *	@param argin Control character to send:\n A - abort all motion programs & moves\n D - disable all PLC & PLCC programs\n K - kill outputs for all motors\n L - close rotary program buffer\n O - do feed hold on all coordinate systems\n Q - quit all programs at end of calculated moves\n R - run working programs in all coordinate systems\n S - step working programs in all coordinate systems\n U - open rotary program buffer\n B - report all motor status words to host\n C - report all coordinate system status words to host\n F - report all motor following errors (unscaled)\n G - report global status words in binary form\n P - report all motor positions (unscaled)\n V - report all motor velocities (unscaled)
 *	@returns Command response from controller card, if any.
 */
//--------------------------------------------------------
Tango::DevString PmacEth::send_ctrl_char(Tango::DevString argin)
{
	DEBUG_STREAM << "PmacEth::SendCtrlChar()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::send_ctrl_char) ENABLED START -----*/
	
	//	Add your own code
	//	POGO has generated a method core with argout allocation.
	//	If you would like to use a static reference without copying,
	//	See "TANGO Device Server Programmer's Manual"
	//		(chapter : Writing a TANGO DS / Exchanging data)
	//------------------------------------------------------------
	Tango::DevString	argout  = new char[256];
	DEBUG_STREAM << "PmacEth::send_ctrl_char(): entering... !" << endl;

	//	Add your own code to control device here
	char c,buf[256];

	if((argin[0]>90 && argin[0]<97)||(argin[0]>122)||(argin[0]<65))
	  {
	    strcpy(argout,"char error");
	    return argout;
	  }
	if(argin[0]>90)
	  argin[0]-=32;
	c=ctrl_char[argin[0]-65];

	if((c==0x02)||(c==0x03)||(c==0x06)||(c==0x07)||(c==0x10)||(c==0x16))
	  if(pmac_get_control_response(sockfd,c,buf,256)<0)
	    strcpy(argout,"error");
	  else
	    strcpy(argout,buf);
	else
	  if(pmac_send_control_char(sockfd,c)<0)
	    strcpy(argout,"error");
	  else
	    strcpy(argout,"success");

	/*----- PROTECTED REGION END -----*/	//	PmacEth::send_ctrl_char
	return argout;
}
//--------------------------------------------------------
/**
 *	Command GlobalStatus related method
 *	Description: Report global status.
 *
 *	@returns Global status words in hex ASCII form.
 */
//--------------------------------------------------------
Tango::DevString PmacEth::global_status()
{
	DEBUG_STREAM << "PmacEth::GlobalStatus()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::global_status) ENABLED START -----*/
	
	//	Add your own code
	//	POGO has generated a method core with argout allocation.
	//	If you would like to use a static reference without copying,
	//	See "TANGO Device Server Programmer's Manual"
	//		(chapter : Writing a TANGO DS / Exchanging data)
	//------------------------------------------------------------
	Tango::DevString	argout  = new char[256];
	//strcpy(argout, "dummy");
	DEBUG_STREAM << "PmacEth::global_status(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[256];
	
	strcpy(buf,"???");
	if(pmac_get_response(sockfd,buf,256)<0)
	  strcpy(argout,"error");
	else
	  strcpy(argout,buf);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::global_status
	return argout;
}
//--------------------------------------------------------
/**
 *	Command CoordSysStatus related method
 *	Description: Report current coordinate system status.
 *
 *	@returns Coordinate system status in hex ASCII form.
 */
//--------------------------------------------------------
Tango::DevString PmacEth::coord_sys_status()
{
	DEBUG_STREAM << "PmacEth::CoordSysStatus()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::coord_sys_status) ENABLED START -----*/
	
	//	Add your own code
	//	POGO has generated a method core with argout allocation.
	//	If you would like to use a static reference without copying,
	//	See "TANGO Device Server Programmer's Manual"
	//		(chapter : Writing a TANGO DS / Exchanging data)
	//------------------------------------------------------------
	Tango::DevString	argout  = new char[32];
	//strcpy(argout, "dummy");
	DEBUG_STREAM << "PmacEth::coord_sys_status(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[32];
	
	strcpy(buf,"??");
	if(pmac_get_response(sockfd,buf,32)<0)
	  strcpy(argout,"error");
	else
	  strcpy(argout,buf);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::coord_sys_status
	return argout;
}
//--------------------------------------------------------
/**
 *	Command GetIVariable related method
 *	Description: Report the value of the I variable indicated in Command Argin.
 *
 *	@param argin I variable number
 *	@returns I variable value
 */
//--------------------------------------------------------
Tango::DevDouble PmacEth::get_ivariable(Tango::DevULong argin)
{
	DEBUG_STREAM << "PmacEth::GetIVariable()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::get_ivariable) ENABLED START -----*/
	
	//	Add your own code
	Tango::DevDouble	argout ;
	DEBUG_STREAM << "PmacEth::get_ivariable(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[16];
	
	sprintf(buf,"I%d",argin);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:get_ivariable","Can't get I variable","Device server GetIVariable",Tango::ERR);
	else
	  argout=atof(buf);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::get_ivariable
	return argout;
}
//--------------------------------------------------------
/**
 *	Command SetIVariable related method
 *	Description: Set the I variable indicated in the first element of Command Argin to
 *               the value specified by the second element of Command Argin.
 *
 *	@param argin I variable number
 */
//--------------------------------------------------------
void PmacEth::set_ivariable(const Tango::DevVarDoubleArray *argin)
{
	DEBUG_STREAM << "PmacEth::SetIVariable()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::set_ivariable) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	sprintf(buf,"I%d=%f",int((*argin)[0]),(*argin)[1]);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:set_ivariable","Can't set I variable","Device server SetIVariable",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::set_ivariable
}
//--------------------------------------------------------
/**
 *	Command GetMVariable related method
 *	Description: Report the value of the M variable indicated in Command Argin.
 *
 *	@param argin M variable number
 *	@returns M variable value
 */
//--------------------------------------------------------
Tango::DevDouble PmacEth::get_mvariable(Tango::DevULong argin)
{
	DEBUG_STREAM << "PmacEth::GetMVariable()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::get_mvariable) ENABLED START -----*/
	
	//	Add your own code
	Tango::DevDouble	argout ;
	DEBUG_STREAM << "PmacEth::get_mvariable(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[16];
	sprintf(buf,"M%d",argin);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:get_mvariable","Can't get M variable","Device server GetMVariable",Tango::ERR);
	else
	  argout=atof(buf);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::get_mvariable
	return argout;
}
//--------------------------------------------------------
/**
 *	Command SetMVariable related method
 *	Description: Set the M variable indicated in the first element of Command Argin to
 *               the value specified by the second element of Command Argin.
 *
 *	@param argin M variable number
 */
//--------------------------------------------------------
void PmacEth::set_mvariable(const Tango::DevVarDoubleArray *argin)
{
	DEBUG_STREAM << "PmacEth::SetMVariable()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::set_mvariable) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	
	sprintf(buf,"M%d=%f",int((*argin)[0]),(*argin)[1]);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:set_mvariable","Can't set M variable","Device server SetMVariable",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::set_mvariable
}
//--------------------------------------------------------
/**
 *	Command GetPVariable related method
 *	Description: Report the value of the P variable indicated in Command Argin.
 *
 *	@param argin P variable number
 *	@returns P variable value
 */
//--------------------------------------------------------
Tango::DevDouble PmacEth::get_pvariable(Tango::DevULong argin)
{
	DEBUG_STREAM << "PmacEth::GetPVariable()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::get_pvariable) ENABLED START -----*/
	
	//	Add your own code
	Tango::DevDouble	argout ;
	DEBUG_STREAM << "PmacEth::get_pvariable(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[16];
	
	sprintf(buf,"P%d",argin);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:get_pvariable","Can't get P variable","Device server GetPVariable",Tango::ERR);
	else
	  argout=atof(buf);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::get_pvariable
	return argout;
}
//--------------------------------------------------------
/**
 *	Command SetPVariable related method
 *	Description: Set the P variable indicated in the first element of Command Argin to
 *               the value specified by the second element of Command Argin.
 *
 *	@param argin P variable number
 */
//--------------------------------------------------------
void PmacEth::set_pvariable(const Tango::DevVarDoubleArray *argin)
{
	DEBUG_STREAM << "PmacEth::SetPVariable()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::set_pvariable) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	
	sprintf(buf,"P%d=%f",int((*argin)[0]),(*argin)[1]);
	DEBUG_STREAM << "SENDING FOLLOWING COMMAND  " << buf << endl;
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:set_pvariable","Can't set P variable","Device server SetPVariable",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::set_pvariable
}
//--------------------------------------------------------
/**
 *	Command SaveIVars related method
 *	Description: Save I variables into non-volatile memory.
 *
 */
//--------------------------------------------------------
void PmacEth::save_ivars()
{
	DEBUG_STREAM << "PmacEth::SaveIVars()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::save_ivars) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	
	strcpy(buf,"SAVE");
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:save_ivars","Can't save I variables","Device server SaveIVars",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::save_ivars
}
//--------------------------------------------------------
/**
 *	Command DownloadFile related method
 *	Description: Download file to PMAC card.
 *
 *	@param argin Name of the file to download to PMAC.
 */
//--------------------------------------------------------
void PmacEth::download_file(Tango::DevString argin)
{
	DEBUG_STREAM << "PmacEth::DownloadFile()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::download_file) ENABLED START -----*/
	
	//	Add your own code
	int fd,i;
	char buf[1024];
	struct stat statbuf;
	DEBUG_STREAM << "File name: " << argin ;
	if((fd=open((const char *)argin,O_RDONLY|O_NONBLOCK))==-1)
	  Tango::Except::throw_exception("Error:download_file","Can't open file","Device server DownloadFile",Tango::ERR);	  
	if(fstat(fd,&statbuf)<0)
	  {
	    close(fd);
	    Tango::Except::throw_exception("Error:download_file","Can't stat file","Device server DownloadFile",Tango::ERR);	  
	  }
	DEBUG_STREAM << "St_size: " << statbuf.st_size;
	for(i=0;i<statbuf.st_size;i+=1024)
	  {
	    if(read(fd,buf,1024)<0)
	      {	
		close(fd);
		Tango::Except::throw_exception("Error:download_file","Can't read file","Device server DownloadFile",Tango::ERR); 
	      }

	    DEBUG_STREAM << "Buffer: " << buf;
	    if(pmac_write_buffer(sockfd,buf,1024)<0)
	      {
		close(fd);
		Tango::Except::throw_exception("Error:download_file","Can't download file to PMAC","Device server DownloadFile",Tango::ERR);	  
	      }
	  }
	close(fd);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::download_file
}
//--------------------------------------------------------
/**
 *	Command UploadVars related method
 *	Description: Upload variables from PMAC.
 *
 *	@param argin Name of the file to save variables to.
 */
//--------------------------------------------------------
void PmacEth::upload_vars(Tango::DevString argin)
{
	DEBUG_STREAM << "PmacEth::UploadVars()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::upload_vars) ENABLED START -----*/
	
	//	Add your own code
	//	Add your own code to control device here

	/*----- PROTECTED REGION END -----*/	//	PmacEth::upload_vars
}
//--------------------------------------------------------
/**
 *	Command UploadProg related method
 *	Description: Not implemented yet.
 *
 *	@param argin Name of the file to upload program to.
 */
//--------------------------------------------------------
void PmacEth::upload_prog(Tango::DevString argin)
{
	DEBUG_STREAM << "PmacEth::UploadProg()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::upload_prog) ENABLED START -----*/
	
	//	Add your own code
	char buf[1024], buf_out[1024];
	const char * file_name = (const char *)argin; 
	filebuf fb;
  	if (!fb.open (file_name, ios::in))
	  Tango::Except::throw_exception("Error:upload_prog","Can't open a file", "Device server UploadProg",Tango::ERR);
  	istream is(&fb);
	while(!is.getline(buf, 1024).eof())
	{
	  if (int(buf[0]) != 59 and int(buf[0]) != 13)
	  {
            unsigned int i = 0;
            do i++; while(i < 1024 and int(buf[i]) != 59);
	    if (i < 1023)
            {
              strncpy(buf_out,buf,i);
	      if(pmac_send_line(sockfd, buf_out) < 0)
                DEBUG_STREAM << "SENDING FAILED" << endl;
              DEBUG_STREAM << "Sent line: " << buf_out << endl;
	      for (int k = 0; k < 20; k++)
                DEBUG_STREAM << "char: " << int(buf_out[k]) << endl;   
            }
            else
            {
              if(pmac_send_line(sockfd, buf)<0)
                DEBUG_STREAM << "SENDING FAILED" << endl;
	      DEBUG_STREAM << "Sent line: " << buf << endl;
		for (int k = 0; k < 20; k++)
                DEBUG_STREAM << "char: " << int(buf[k]) << endl;   
            }
	  }
	  for (unsigned int j = 0; j < 1024; j++)
	    buf[j] = buf_out[j] = char(NULL);
	}
	fb.close();

	/*----- PROTECTED REGION END -----*/	//	PmacEth::upload_prog
}
//--------------------------------------------------------
/**
 *	Command GetMotorNo related method
 *	Description: Get current motor number.
 *
 *	@returns Current motor number.
 */
//--------------------------------------------------------
Tango::DevShort PmacEth::get_motor_no()
{
	DEBUG_STREAM << "PmacEth::GetMotorNo()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::get_motor_no) ENABLED START -----*/
	
	//	Add your own code
	Tango::DevShort	argout ;
	DEBUG_STREAM << "PmacEth::get_motor_no(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[16];
	
	strcpy(buf,"#");
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:get_motor_no","Can't get motor number","Device server GetMotorNo",Tango::ERR);
	else
	  argout=atoi(buf);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::get_motor_no
	return argout;
}
//--------------------------------------------------------
/**
 *	Command SetMotorNo related method
 *	Description: Set current motor number.
 *
 *	@param argin Motor number.
 */
//--------------------------------------------------------
void PmacEth::set_motor_no(Tango::DevShort argin)
{
	DEBUG_STREAM << "PmacEth::SetMotorNo()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::set_motor_no) ENABLED START -----*/
	
	//	Add your own code
	char buf[16];
	
	sprintf(buf,"#%d",argin);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:set_motor_no","Can't set motor number","Device server SetMotorNo",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::set_motor_no
}
//--------------------------------------------------------
/**
 *	Command DefineCoordSys related method
 *	Description: Define a coordinate system for the current motor axis, specifying scale factor & offset.
 *
 *	@param argin Scale factor, Offset
 */
//--------------------------------------------------------
void PmacEth::define_coord_sys(const Tango::DevVarDoubleArray *argin)
{
	DEBUG_STREAM << "PmacEth::DefineCoordSys()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::define_coord_sys) ENABLED START -----*/
	
	//	Add your own code
	//	char buf[16];
	
	//sprintf(buf,"#1->...",argin);
	//if(pmac_get_response(sockfd,buf,16)<0)
	//  printf("error!\n");
	//else
	//  printf("success\n");

	/*----- PROTECTED REGION END -----*/	//	PmacEth::define_coord_sys
}
//--------------------------------------------------------
/**
 *	Command GetCoordSys related method
 *	Description: Report axis definition of current motor in current coordinate system.
 *
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevString PmacEth::get_coord_sys()
{
	DEBUG_STREAM << "PmacEth::GetCoordSys()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::get_coord_sys) ENABLED START -----*/
	
	//	Add your own code
	//	POGO has generated a method core with argout allocation.
	//	If you would like to use a static reference without copying,
	//	See "TANGO Device Server Programmer's Manual"
	//		(chapter : Writing a TANGO DS / Exchanging data)
	//------------------------------------------------------------
	Tango::DevString	argout  = new char[16];
	//strcpy(argout, "dummy");
	DEBUG_STREAM << "PmacEth::get_coord_sys(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[16];
	
	strcpy(buf,"&");
	if(pmac_get_response(sockfd,buf,16)<0)
	  strcpy(argout,"error");
	else
	  strcpy(argout,buf);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::get_coord_sys
	return argout;
}
//--------------------------------------------------------
/**
 *	Command OnlineCmd related method
 *	Description: Executes an online command on Pmac.
 *
 *	@param argin Cmd String
 *	@returns Cmd Output
 */
//--------------------------------------------------------
Tango::DevString PmacEth::online_cmd(Tango::DevString argin)
{
	DEBUG_STREAM << "PmacEth::OnlineCmd()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::online_cmd) ENABLED START -----*/
	
	//	Add your own code
	//	POGO has generated a method core with argout allocation.
	//	If you would like to use a static reference without copying,
	//	See "TANGO Device Server Programmer's Manual"
	//		(chapter : Writing a TANGO DS / Exchanging data)
	//------------------------------------------------------------
	Tango::DevString	argout  = new char[8192];

	DEBUG_STREAM << "PmacEth::online_cmd(): entering... !" << endl;
	int cmd_length = strlen(argin);
	char buf[8192];
	strcpy(buf,argin);
	int nrOfChar = pmac_get_response(sockfd,buf,8192);
	if(nrOfChar < 0)
	  strcpy(argout,"Error");
	else
	{
	  if (int(buf[0]) == 6)
	    strcpy(argout,"Acknowledge");
	  else
 	    strncpy(argout,buf,nrOfChar);
	}

	/*----- PROTECTED REGION END -----*/	//	PmacEth::online_cmd
	return argout;
}
//--------------------------------------------------------
/**
 *	Command EnablePLC related method
 *	Description: Enables PLC on Pmac.
 *
 *	@param argin PLC program nr
 */
//--------------------------------------------------------
void PmacEth::enable_plc(Tango::DevShort argin)
{
	DEBUG_STREAM << "PmacEth::EnablePLC()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::enable_plc) ENABLED START -----*/
	
	//	Add your own code
	//TODO allow to pass list of PLC
	DEBUG_STREAM << "PmacEth::enable_plc(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[16];
	
	sprintf(buf,"ENABLE PLC %d",argin);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:enable_plc","Can't enable plc","Device server EnablePLC",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::enable_plc
}
//--------------------------------------------------------
/**
 *	Command DisablePLC related method
 *	Description: Disables PLC on Pmac.
 *
 *	@param argin PLC prog nr
 */
//--------------------------------------------------------
void PmacEth::disable_plc(Tango::DevShort argin)
{
	DEBUG_STREAM << "PmacEth::DisablePLC()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::disable_plc) ENABLED START -----*/
	
	//	Add your own code
	//TODO allow to pass list of PLC
	DEBUG_STREAM << "PmacEth::disable_plc(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[16];
	
	sprintf(buf,"DISABLE PLC %d",argin);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:disable_plc","Can't disable plc","Device server DisablePLC",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::disable_plc
}
//--------------------------------------------------------
/**
 *	Command RunMotionProg related method
 *	Description: Run motion program on Pmac.
 *
 *	@param argin Motion program nr
 */
//--------------------------------------------------------
void PmacEth::run_motion_prog(Tango::DevShort argin)
{
	DEBUG_STREAM << "PmacEth::RunMotionProg()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::run_motion_prog) ENABLED START -----*/
	
	//	Add your own code
	//TODO allow to pass list of motion programs
	DEBUG_STREAM << "PmacEth::run_motion_prog(): entering... !" << endl;

	//	Add your own code to control device here
	char buf[16];
	
	sprintf(buf,"B%dR",argin);
	if(pmac_get_response(sockfd,buf,16)<0)
	  Tango::Except::throw_exception("Error:run_motion_prog","Can't run motion program","Device server RunMotionProg",Tango::ERR);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::run_motion_prog
}
//--------------------------------------------------------
/**
 *	Command GetMotorPos related method
 *	Description: Get motor position.
 *
 *	@param argin Motor nr
 *	@returns Motor position
 */
//--------------------------------------------------------
Tango::DevDouble PmacEth::get_motor_pos(Tango::DevShort argin)
{
	DEBUG_STREAM << "PmacEth::GetMotorPos()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PmacEth::get_motor_pos) ENABLED START -----*/
	
	//	Add your own code
	Tango::DevDouble	argout ;
	char buf[2048];

	sprintf(buf,"#%dP",argin);
	if(pmac_get_response(sockfd,buf,2048)<0)
	  Tango::Except::throw_exception("Error:get_motor_pos","Can't get motor position","Device server GetMotorPos",Tango::ERR);
	else
	  argout=atof(buf);

	/*----- PROTECTED REGION END -----*/	//	PmacEth::get_motor_pos
	return argout;
}
//------------------------------------------------------------------
Tango::DevVarDoubleArray *PmacEth::get_pvariable_range(const Tango::DevVarULongArray *argin)
//Tango::DevVarDoubleArray* PmacEth::get_pvariablerange(const Tango::DevVarULongArray *argin)
{
	Tango::DevVarDoubleArray*    argout = new Tango::DevVarDoubleArray();
    DEBUG_STREAM << "PmacEth::get_pvariablerange(): entering... !" << endl;

    //  Add your own code to control device here
    if(argin->length() != 2)
      Tango::Except::throw_exception( (const char*) ("TANGO_DEVICE_ERROR"),
                                        (const char*) ("Invalid number of parameters. Expects 2: beginRange and endRange\n"),
                                        (const char*) ("PmacEth::get_pvariablerange"));

    const unsigned long begin        = (*argin)[0];
    const unsigned long end          = (*argin)[1];

    if(begin > end) 
      Tango::Except::throw_exception( (const char*) ("TANGO_DEVICE_ERROR"),
                                        (const char*) ("Wrong parameters: begin of range has to be lower than end.\n"),
                                        (const char*) ("PmacEth::get_pvariablerange"));
    if ((end - begin) > 99)
      Tango::Except::throw_exception( (const char*) ("TANGO_DEVICE_ERROR"),
                                        (const char*) ("Wrong parameters: max range is 100 variables.\n"),
                                        (const char*) ("PmacEth::get_pvariablerange"));
    char buf[1400];

    sprintf(buf,"P%d..%d",begin,end);
    int nrOfChars = pmac_get_response(sockfd,buf,1400);
    if(nrOfChars < 0)
      Tango::Except::throw_exception("Error:get_pvariable","Can't get P variables","Device server GetPVariableRange",Tango::ERR);
    else
    {
      vector<double> pvars;
      const char delim[2] = {char(13), char(6)};
      char *      save;
      char *      p;

      for (p = strtok_r(buf, delim, &save); p; p = strtok_r(NULL, delim, &save))
      {
        pvars.push_back(atof(p));
        //printf("%s\t%f\n",p, atof(p));
      }

      
      argout->length(pvars.size());

      vector<double>::iterator it;
      int i;
      for (i = 0, it = pvars.begin(); it != pvars.end(); it++, i++)
        (*argout)[i] = *it;
    }
    return argout;
}
Tango::DevVarStringArray* PmacEth::list_plc(Tango::DevShort argin)
{
	DEBUG_STREAM << "PmacEth::list_plc(): entering... !" << endl;
	
	//	Add your own code to control device here
	Tango::DevVarStringArray	*argout = new Tango::DevVarStringArray();
	char buf[128],in_buf[128];
	vector<string> plc;
	
	sprintf(buf,"LIST PLC %d",argin);

	if(pmac_send_line(sockfd,buf)<0)
	  Tango::Except::throw_exception("Error:list_plc","Couldn't ask for listing plc","Device server ListPLC",Tango::ERR);

	while(true)
 	{
	  if (pmac_get_line(sockfd,in_buf,128)<0)
            Tango::Except::throw_exception("Error:list_plc","Couldn't read line","Device server ListPLC",Tango::ERR);
	 
	  if (int(in_buf[0]) == 6)
	    break;
 	  plc.push_back(string(in_buf));
	  for (unsigned int i = 0; i < 128; i++)
	    in_buf[i] = char(NULL);
	}
	
	argout->length(plc.size());
	for(unsigned int i = 0; i < plc.size(); i++)
	  (*argout)[i] = CORBA::string_dup(const_cast<char *>(plc[i].c_str()));

	return argout;
}
const char PmacEth::ctrl_char[26]={0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A};


/*----- PROTECTED REGION END -----*/	//	PmacEth::namespace_ending
} //	namespace
